behaviors:
  "RollerBall":
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      grad_clip: 4
      clip_param: 0.4
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          grad_clip: 4
          vis_encode_type: simple
          goal_conditioning_type: hyper
          deterministic: false
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 100000
    time_horizon: 64
    summary_freq: 10000
    threaded: false
    
    
    "Pacman":
      trainer_type: ppo
      hyperparameters:
        batch_size: 1024
        buffer_size: 10240
        learning_rate: 0.003
        beta: 0.005
        epsilon: 0.2
        lambd: 0.95
        num_epoch: 3
        learning_rate_schedule: linear
        beta_schedule: linear
        epsilon_schedule: linear
      network_settings:
        normalize: false
        hidden_units: 128
        num_layers: 2
        grad_clip: 4
        clip_param: 0.4
        vis_encode_type: simple
        goal_conditioning_type: hyper
        deterministic: false
      reward_signals:
        extrinsic:
          gamma: 0.99
          strength: 1.0
          network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            grad_clip: 4
            vis_encode_type: simple
            goal_conditioning_type: hyper
            deterministic: false
      keep_checkpoints: 5
      checkpoint_interval: 500000
      max_steps: 100000
      time_horizon: 64
      summary_freq: 10000
      threaded: false